import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dataRoot = resolve(root, "../tendercells-ui/src/features/builder/data");
const out = resolve(root, "backend/src/mcp/v2/generatedBuilderContent.ts");
async function load(folder: string, suffix: string) {
  const files = (await readdir(resolve(dataRoot, folder))).filter(n => n.endsWith(suffix)).sort();
  const ids = new Set<string>();
  return Promise.all(files.map(async name => {
    const data = JSON.parse(await readFile(resolve(dataRoot, folder, name), "utf8"));
    if (typeof data.id !== "string" || ids.has(data.id)) throw new Error(`Invalid or duplicate content id: ${name}`);
    ids.add(data.id);
    return { sourceFile: `applications/tendercells_ui/test_output/tendercells-ui/src/features/builder/data/${folder}/${name}`, data };
  }));
}
const missions = await load("missions", ".mission.json");
const projects = await load("projects", ".project.json");
const manifest = JSON.parse(await readFile(resolve(dataRoot, "missions/manifest.json"), "utf8"));
if (manifest.missions.length !== missions.length || manifest.missions.some((m: { id: string; file: string }) => !missions.some(x => x.data.id === m.id && x.sourceFile.endsWith('/' + m.file)))) throw new Error("Mission manifest mismatch");
const result = '// Generated by tools/generate-builder-mcp.mts. Do not edit.\nimport type { BuilderContent } from "./contentTypes.js";\nexport const BUILDER_CONTENT: BuilderContent = ' + JSON.stringify({ missions, projects }, null, 2) + ';\n';
if (process.argv.includes('--check')) {
  const current = await readFile(out, 'utf8').catch(() => '');
  if (current.replace(/\r\n/g, '\n') !== result) throw new Error('Builder MCP content is stale. Run npm run mcp:content');
} else { await mkdir(dirname(out), { recursive: true }); await writeFile(out, result); }
console.log(`Builder MCP content: ${missions.length} missions, ${projects.length} projects`);
