\
/**
 * SCAFFOLD — reconcile with current main before use.
 *
 * Run from applications/tendercells_ui/test_output/express-api.
 * Reads the existing Builder JSON and generates a TypeScript artifact for MCP.
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, basename } from "node:path";

const expressApiRoot = process.cwd();
const builderData = resolve(expressApiRoot, "../tendercells-ui/src/features/builder/data");
const missionDir = resolve(builderData, "missions");
const projectDir = resolve(builderData, "projects");
const out = resolve(expressApiRoot, "backend/src/mcp/v2/generatedBuilderContent.ts");

async function readJson(path: string) {
  return JSON.parse(await readFile(path, "utf8"));
}
async function load(dir: string, suffix: string) {
  const names = (await readdir(dir)).filter((n) => n.endsWith(suffix)).sort();
  return Promise.all(names.map(async (name) => ({
    sourceFile: name,
    data: await readJson(resolve(dir, name)),
  })));
}

const missions = await load(missionDir, ".mission.json");
const projects = await load(projectDir, ".project.json");

const payload = `// AUTO-GENERATED by tools/generate-builder-mcp.mts. DO NOT EDIT.\n` +
  `export const GENERATED_BUILDER_CONTENT = ${JSON.stringify({ missions, projects }, null, 2)} as const;\n`;

await mkdir(resolve(expressApiRoot, "backend/src/mcp/v2"), { recursive: true });
await writeFile(out, payload, "utf8");
console.log(`builder MCP content → ${out} (${missions.length} missions, ${projects.length} projects)`);
